Repository juice-shop/juice-shop-ctf, pull requests merged in 2025-02, with the labels that each got.

#148 Add paid hints back to CTFd exporter
  lib/generators/ctfd.js
Labels: size/M

#151 Fixed broken link
  .github/workflows/greetings.yml
Labels: size/XS

#154 fixed broken links
  README.md
Labels: size/S

#153 pull request template added
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/S
